# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_MXC) += lec-imx8mm-auoB101UAN01-mipi-panel.dtb \
			  lec-imx8mm-hydis-hv150ux2-lvds-panel.dtb \
			  lec-imx8mm-ov5647.dtb \
			  lec-imx8mm-imx219.dtb \
			  lec-imx8mm-ov13855.dtb \
			  lec-imx8mm.dtb
